// <auto-generated />
using System;
using ForumApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ForumApp.Migrations
{
    [DbContext(typeof(ForumDbContext))]
    [Migration("20231226094518_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ForumApp.Data.Models.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("938bfd48-3904-4843-a8a0-ad5c0f6b2cdb"),
                            Content = "Explore diverse posts on our app—inspiring stories, helpful tips, and entertaining moments await. Discover a world of content today!",
                            Title = "My first post"
                        },
                        new
                        {
                            Id = new Guid("a081c901-a141-4bdf-badf-b10a129ca96e"),
                            Content = "Discover a myriad of posts in our app—each a gem of wisdom, a burst of joy. Explore diverse content daily!",
                            Title = "My second post"
                        },
                        new
                        {
                            Id = new Guid("346039ca-b868-4bc8-83a3-f1cbad7a8cd6"),
                            Content = "Dive into a tapestry of posts on our app—uncover joy, insights, and surprises. Your daily dose of delightful content awaits!",
                            Title = "My third post"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
